config/routes.rb
Rails.application.routes.draw do
  resources :pendaftarans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/paket_kursus', to: 'paket_kursus#index'
  root 'paket_kursus#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/harga_kursu.rb
class HargaKursu < ApplicationRecord
end

app/models/pendaftaran.rb
class Pendaftaran < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paket_kursus_controller.rb
class PaketKursusController < ApplicationController
    def index
        
    end

    def show
        
    end

    def new
        
    end

    def edit
        
    end

    def create
        
    end

    def update
        
    end

    def destroy
        
    end
end

app/controllers/pendaftarans_controller.rb
class PendaftaransController < ApplicationController
  before_action :set_pendaftaran, only: %i[ show edit update destroy ]

  # GET /pendaftarans or /pendaftarans.json
  def index
    @pendaftarans = Pendaftaran.all
  end

  # GET /pendaftarans/1 or /pendaftarans/1.json
  def show
  end

  # GET /pendaftarans/new
  def new
    @pendaftaran = Pendaftaran.new
  end

  # GET /pendaftarans/1/edit
  def edit
  end

  # POST /pendaftarans or /pendaftarans.json
  def create
    @pendaftaran = Pendaftaran.new(pendaftaran_params)

    respond_to do |format|
      if @pendaftaran.save
        format.html { redirect_to @pendaftaran, notice: "Pendaftaran was successfully created." }
        format.json { render :show, status: :created, location: @pendaftaran }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pendaftaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pendaftarans/1 or /pendaftarans/1.json
  def update
    respond_to do |format|
      if @pendaftaran.update(pendaftaran_params)
        format.html { redirect_to @pendaftaran, notice: "Pendaftaran was successfully updated." }
        format.json { render :show, status: :ok, location: @pendaftaran }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pendaftaran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pendaftarans/1 or /pendaftarans/1.json
  def destroy
    @pendaftaran.destroy
    respond_to do |format|
      format.html { redirect_to pendaftarans_url, notice: "Pendaftaran was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pendaftaran
      @pendaftaran = Pendaftaran.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pendaftaran_params
      params.require(:pendaftaran).permit(:nama, :alamat, :hobi, :no_hp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paket_kursus_helper.rb
module PaketKursusHelper
end

app/helpers/pendaftarans_helper.rb
module PendaftaransHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paket_kursus/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
 
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
 
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
 
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

<div class="container">
    <div class="row pt-3">
        <div class="col-md-6">
            <h2>Selamat Belajar Ruby</h2>
            
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="..." alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pendaftarans/_form.html.erb
<%= form_with(model: pendaftaran) do |form| %>
  <% if pendaftaran.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pendaftaran.errors.count, "error") %> prohibited this pendaftaran from being saved:</h2>

      <ul>
        <% pendaftaran.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :alamat %>
    <%= form.text_field :alamat %>
  </div>

  <div class="field">
    <%= form.label :hobi %>
    <%= form.text_field :hobi %>
  </div>

  <div class="field">
    <%= form.label :no_hp %>
    <%= form.text_field :no_hp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pendaftarans/edit.html.erb
<h1>Editing Pendaftaran</h1>

<%= render 'form', pendaftaran: @pendaftaran %>

<%= link_to 'Show', @pendaftaran %> |
<%= link_to 'Back', pendaftarans_path %>

app/views/pendaftarans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pendaftarans</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Alamat</th>
      <th>Hobi</th>
      <th>No hp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pendaftarans.each do |pendaftaran| %>
      <tr>
        <td><%= pendaftaran.nama %></td>
        <td><%= pendaftaran.alamat %></td>
        <td><%= pendaftaran.hobi %></td>
        <td><%= pendaftaran.no_hp %></td>
        <td><%= link_to 'Show', pendaftaran %></td>
        <td><%= link_to 'Edit', edit_pendaftaran_path(pendaftaran) %></td>
        <td><%= link_to 'Destroy', pendaftaran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pendaftaran', new_pendaftaran_path %>

app/views/pendaftarans/new.html.erb
<h1>New Pendaftaran</h1>

<%= render 'form', pendaftaran: @pendaftaran %>

<%= link_to 'Back', pendaftarans_path %>

app/views/pendaftarans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @pendaftaran.nama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @pendaftaran.alamat %>
</p>

<p>
  <strong>Hobi:</strong>
  <%= @pendaftaran.hobi %>
</p>

<p>
  <strong>No hp:</strong>
  <%= @pendaftaran.no_hp %>
</p>

<%= link_to 'Edit', edit_pendaftaran_path(@pendaftaran) %> |
<%= link_to 'Back', pendaftarans_path %>